# Generated by Django 2.1.3 on 2018-12-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perfil_id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil_usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
