# Generated by Django 2.1.3 on 2018-12-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_auto_20181211_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='perfil_mensagem',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='perfil_usuario',
            field=models.CharField(max_length=1000),
        ),
    ]
